test_setUpCisco (__main__.test_setUpCisco) ... ERROR

======================================================================
ERROR: test_setUpCisco (__main__.test_setUpCisco)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.amd/netapp2/vol/vol1/home2/smath/systest/tests/glcr/ha_imc/setUpCisco.py", line 114, in test_setUpCisco
    self.cisco.configure_ipv4_vlan_interface(ip_addr=haimc_var['cisco_active_slot2_ip_mask'],intf=haimc_var['port_cisco_active_4slot2'],vlan=haimc_var['vlan4slot2'],vrf=haimc_var['vrf_name2'])
  File "../../lib/py/CISCO.py", line 340, in configure_ipv4_vlan_interface
    self.cmd("exit")
  File "../../lib/py/CISCO.py", line 182, in cmd
    raise misc.TestError("pexpect timeout")
TestError: 'pexpect timeout'

----------------------------------------------------------------------
Ran 1 test in 603.757s

FAILED (errors=1)
